source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'pg'
gem 'bcrypt', '~> 3.1.7'
gem 'turbolinks'
gem 'devise'

# Front end gems
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'semantic-ui-sass', github: 'doabit/semantic-ui-sass'

group :development, :test do
  gem 'byebug'
  gem 'spring'
  gem 'mailcatcher'
end
